### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tests'

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#10]
Currently https://code.launchpad.net/~snappy-dev/+recipe/snapcraft-daily fails to build:

   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:170: python3.4 setup.py test 
running test
running egg_info
creating snapcraft.egg-info
writing dependency_links to snapcraft.egg-info/dependency_links.txt
writing top-level names to snapcraft.egg-info/top_level.txt
writing snapcraft.egg-info/PKG-INFO
writing manifest file 'snapcraft.egg-info/SOURCES.txt'
reading manifest file 'snapcraft.egg-info/SOURCES.txt'
writing manifest file 'snapcraft.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    test_suite='snapcraft.tests',
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 146, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 167, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 157, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 157, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 125, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'tests'
E: pybuild pybuild:262: test: plugin distutils failed with: exit code=1: python3.4 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 3.4 --dir . returned exit code 13
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 25

Launchpad Details: [#LP1507573](https://bugs.launchpad.net/bugs/1507573) Daniel Holbach - 2015-10-19 09:49:22 -0300

**Comment by sergiusens** [comment]
Installing python3-autopilot fixes it.

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1507573/comments/1) Daniel Holbach - 2015-10-19 10:06:53 -0300

**Comment by sergiusens** [comment]
Confirmed that the daily recipe is now building fine.

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1507573/comments/2) Leo Arias - 2015-10-28 20:59:41 -0300
