### ISSUE TITLE
Help crashes if specified plugin does not exist

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#13]
daniel@daydream:~/dev/snappy/snapcraft$ ./bin/snapcraft help plugin
The plugin does not exist. Use one of the following:
ant
autotools
catkin
cmake
copy
go
jdk
make
maven
python2
python3
qml
roscore
scons
tar-content
Traceback (most recent call last):
  File "./bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/home/daniel/dev/snappy/snapcraft/snapcraft/main.py", line 115, in main
    args.func(args)
  File "/home/daniel/dev/snappy/snapcraft/snapcraft/help.py", line 50, in topic
    _module_help(args.topic, args.devel)
  File "/home/daniel/dev/snappy/snapcraft/snapcraft/help.py", line 68, in _module_help
    if module.__doc__ and devel:
UnboundLocalError: local variable 'module' referenced before assignment
daniel@daydream:~/dev/snappy/snapcraft$

Launchpad Details: [#LP1510954](https://bugs.launchpad.net/bugs/1510954) Daniel Holbach - 2015-10-28 11:19:12 -0300

**Comment by sergiusens** [comment]
Confirmed that there is no traceback anymore.

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1510954/comments/1) Leo Arias - 2015-10-29 01:14:22 -0300
