### ISSUE TITLE
User friendly error missing when using go's source entry incorrectly

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#20]
daniel@daydream:~/dev/apps/bwm-ng.snap$ cat snapcraft.yaml 
name: bwm-ng
version: 0.6-3.2
vendor: Daniel Holbach <email address hidden>
summary: small and simple console-based bandwidth monitor
description:
 Bandwidth Monitor NG is a small and simple console-based live network and 
 disk io bandwidth monitor for Linux, BSD, Solaris, Mac OS X and others
icon: ubuntu.png
binaries:
  bwm-ng:
    exec: usr/bin/bwm-ng

parts:
  bwm-ng:
    type: go
    source: .
    stage-packages: [bwm-ng]
daniel@daydream:~/dev/apps/bwm-ng.snap$ ls
image  parts  snapcraft.yaml  ubuntu.png
daniel@daydream:~/dev/apps/bwm-ng.snap$ snapcraft 
Skipping pull bwm-ng (already ran)
Skipping build bwm-ng (already ran)
Skipping stage bwm-ng (already ran)
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 80, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 99, in assemble
    snap(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 81, in snap
    cmd(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 325, in cmd
    shutil.rmtree(common.get_snapdir())
  File "/usr/lib/python3.4/shutil.py", line 459, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.4/shutil.py", line 457, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/daniel/dev/apps/bwm-ng.snap/snap'
daniel@daydream:~/dev/apps/bwm-ng.snap$

Launchpad Details: [#LP1499240](https://bugs.launchpad.net/bugs/1499240) Daniel Holbach - 2015-09-24 06:02:52 -0300

**Comment by sergiusens** [comment]
Is this bug still valid? I can reproduce a different bug when using plugin go and source . (if '.' has nothing of the kind expected in a go project')

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1499240/comments/1) Sergio Schvezov - 2015-10-14 17:16:18 -0300

**Comment by sergiusens** [comment]
Yep, I see the same issue as you.

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1499240/comments/2) Daniel Holbach - 2015-10-16 06:36:46 -0300
