### ISSUE TITLE
snapcraft throws FileExistsError: with very simple Python snap

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#21]
Trying out snapcraft, starting with a very simple project. I wrote a very simple Python service:

import time

i = 0

while i < 1000:
    print("this is a python snap: " + str(i))
    i += 1
    time.sleep(5)

I wrote the following snpacraft.yaml:

name: python-snap
version: 1
vendor: Rick Spencer <email address hidden>
summary: a test of snapcraft
description: a longer test of snapcraft
icon: icon.png

parts:
 loop:
  type: python3-project
  source: ./hello-python.

I ran $snapcraft stage

and got this error:
py3versions -i
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 80, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 328, in cmd
    common.env = config.build_env_for_part(part)
  File "/usr/lib/python3/dist-packages/snapcraft/yaml.py", line 221, in build_env_for_part
    env += part.env(part.installdir)
  File "/usr/lib/python3/dist-packages/snapcraft/plugin.py", line 282, in env
    return getattr(self.code, 'env')(root)
  File "/usr/lib/python3/dist-packages/snapcraft/plugins/python3_project.py", line 38, in env
    root, 'usr', 'lib', self.python_version, 'dist-packages')]
  File "/usr/lib/python3/dist-packages/snapcraft/plugins/python3_project.py", line 106, in python_version
    return self.run_output(['py3versions', '-i'])
  File "/usr/lib/python3/dist-packages/snapcraft/__init__.py", line 80, in run_output
    self.makedirs(cwd)
  File "/usr/lib/python3/dist-packages/snapcraft/__init__.py", line 112, in makedirs
    os.makedirs(d, exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/rick/Projects/phw/parts/loop/build'

Launchpad Details: [#LP1499424](https://bugs.launchpad.net/bugs/1499424) Rick Spencer - 2015-09-24 12:18:27 -0300

**Comment by sergiusens** [comment]
With Sergio's branch now this snapcraft.yaml exists with the following error message:

Unrecognized source './test.py' for part 'loop': Local source is not a directory.

That's good, but how can we make it clearer that the local source must be a directory?

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1499424/comments/1) Leo Arias - 2015-10-14 20:27:14 -0300
