### ISSUE TITLE
[copy] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#41]
I'm sure I'm using it wrong, bug snapcraft shouldn't crash:

name: bwm-ng
version: 0.6-3.2
vendor: Daniel Holbach <email address hidden>
summary: small and simple console-based bandwidth monitor
description:
 Bandwidth Monitor NG is a small and simple console-based live network and 
 disk io bandwidth monitor for Linux, BSD, Solaris, Mac OS X and others
icon: ubuntu.png
binaries:
  bwm-ng:
    exec: usr/bin/bwm-ng

parts:
  bwm-ng:
    type: copy
    files: .
    stage-packages: [bwm-ng]

aniel@daydream:~/dev/apps/bwm-ng.snap$ snapcraft build 
Skipping pull bwm-ng (already ran)
Building bwm-ng
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 80, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 331, in cmd
    if not getattr(part, cmd)(force=force):
  File "/usr/lib/python3/dist-packages/snapcraft/plugin.py", line 208, in build
    if not getattr(self.code, 'build')():
  File "/usr/lib/python3/dist-packages/snapcraft/plugins/copy.py", line 31, in build
    dst = self.options.files[src]
TypeError: string indices must be integers
daniel@daydream:~/dev/apps/bwm-ng.snap$

Launchpad Details: [#LP1499249](https://bugs.launchpad.net/bugs/1499249) Daniel Holbach - 2015-09-24 06:15:26 -0300

**Comment by sergiusens** [comment]
The schema and exception handling plugin work should have fixed this
