### ISSUE TITLE
ros-catkin-plugin: ros distro issue

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#43]
Snapping roscore
Traceback (most recent call last):
  File "../../bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/home/victor/ros-catkin-plugin/snapcraft/main.py", line 80, in main
    args.func(args)
  File "/home/victor/ros-catkin-plugin/snapcraft/cmds.py", line 99, in assemble
    snap(args)
  File "/home/victor/ros-catkin-plugin/snapcraft/cmds.py", line 92, in snap
    meta.create(config.data, arches)
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 57, in create
    _write_package_yaml(meta_dir, config_data, arches)
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 68, in _write_package_yaml
    package_yaml = _compose_package_yaml(meta_dir, config_data, arches)
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 139, in _compose_package_yaml
    services = _wrap_services(services)
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 225, in _wrap_services
    startwrap = _wrap_exe(startparts[0])
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 206, in _wrap_exe
    _write_wrap_exe(wrapexec, wrappath)
  File "/home/victor/ros-catkin-plugin/snapcraft/meta.py", line 173, in _write_wrap_exe
    with open(wrappath, 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/ros-catkin-plugin/examples/ros/snap/opt/ros/jade/bin/roscore.wrapper'
victor@ubuntu:~/ros-catkin-plugin/examples/ros$ ls snap/opt/ros/indigo/^C
victor@ubuntu:~/ros-catkin-plugin/examples/ros$ vi snapcraft.yaml 
victor@ubuntu:~/ros-catkin-plugin/examples/ros$ ../../bin/snapcraft

Launchpad Details: [#LP1500922](https://bugs.launchpad.net/bugs/1500922) Victor Mayoral - 2015-09-29 12:20:29 -0300

**Comment by ted-gould** [comment]
This was fixed by changing the path in the example to indigo.
